name: assess-tests
on: [push]
jobs:
  run-code-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x', 'pypy-3.6', 'pypy-3.7']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install codecov
      - run: pip install coveralls
      - run: pip install nose-show-skipped
      - run: pip install mock
      - run: python setup.py install
      - run: coverage run assess-tests.py
      - run: codecov
      - run: coveralls
            
